version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: budget-tracker_db
    environment:
      POSTGRES_DB: budget_tracker_db
      POSTGRES_USER: budget_tracker
      POSTGRES_PASSWORD: budget_tracker_password
    ports:
      - "15436:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data: